# This gitlab yaml template belongs to sidero ltd
# It is is developed in line with this project https://gitlab.com/sideroltd/terraform/-/pipelines
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages

image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
    - 'AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}' 
    - 'AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}' 
    - 'AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}'


variables:
  PLAN: plan.tfplan

cache:
  paths:
    - .terraform

before_script:
  - terraform --version
  - terraform init

stages:          # List of stages for jobs, and their order of execution
  - build
  - validate
  - plan
  - apply

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Initializing the Terraform environment..."
    - terraform init -backend=false
    - echo "Initilization complete."

module-validate:   # This job runs in the test stage.
  stage: validate    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Running terraform validation... This will take some time depending on the module."
    - terraform validate
    - terraform fmt -check

lint-test:   # This job also runs in the test stage.
  stage: validate    # It can run at the same time as unit-test-job (in parallel).
  script:
    - echo "Linting code... This will take about 10 seconds."
    - sleep 10
    - echo "No lint issues found."


plan-job:      # This job runs in the deploy stage.
  stage: plan  # It only runs when *both* jobs in the validate stage complete successfully.
  script:
    - echo "running Terraform plan..."
    - 
    - echo "Terraform plan completed successfully."

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
